### ISSUE TITLE
Nuxt-Bridge, Vite and nuxt-windicss

### ISSUE THREAD

**Issue by thomas4Bitcraft** [windicss/nuxt-windicss#141] opened 2021-12-02 22:46 UTC
I'm currently trying to update my app to nuxt-bridge, but it seems to be broken because of the windicss package.

I use the versions:
"nuxt-edge": "latest",
"nuxt-windicss": "^2.0.12",
"@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27307420.6a25d3e"

And when running `npm run dev` it throws the error:
```
* nuxt_plugin_helper_619f8ab8 in ./.nuxt/index.js                                                                                                   
* ~/lib/models/Course in ./node_modules/windicss-webpack-plugin/dist/loaders/pitcher.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js!./pages/search.vue?vue&type=script&lang=js&, ./node_modules/windicss-webpack-plugin/dist/loaders/pitcher.js!./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/windicss-webpack-plugin/dist/loaders/transform-template.js!./pages/dashboard/call-seminars.vue?vue&type=script&lang=js&
```

Any idea why this is happening? In general i want to use vite to build the app with enabling it inside nuxt.config.js:

```
bridge: {
    vite: true,
  },
```

**Comment by harlan-zw** [comment] 2021-12-07 12:04
Hey @thomas4Bitcraft 

Seems as though this is using the webpack build :thinking: Would you be able to provide a reproduction repo, it's a bit hard to replicate exactly what the issue is

**Comment by harlan-zw** [comment] 2021-12-09 03:15
If you are using the webpack build, then this may be resolved in the latest version, I sorted out a pitching logic issue in the webpack plugin

**Closed** 2021-12-20 13:54 UTC
